package com.example.newsapplication.utils

object CountyList {

    /**
     * Country List
     * */
    val countryList: List<Pair<String, String>> = listOf(
        Pair("Argentina", "ar"),
        Pair("Australia", "au"),
        Pair("Austria", "at"),
        Pair("Belgium", "be"),
        Pair("Brazil", "br"),
        Pair("Bulgaria", "bg"),
        Pair("Canada", "ca"),
        Pair("China", "cn"),
        Pair("Colombia", "co"),
        Pair("Czech Repulic", "cz"),
        Pair("Egypt", "eg"),
        Pair("France", "fr"),
        Pair("Germany", "de"),
        Pair("Greece", "gr"),
        Pair("Hong Kong", "hk"),
        Pair("Hungary", "hu"),
        Pair("India", "in"),
        Pair("Indonesia", "id"),
        Pair("Ireland", "ie"),
        Pair("Israel", "il"),
        Pair("Italy", "it"),
        Pair("Japan", "jp"),
        Pair("Latvia", "lt"),
        Pair("Lithuania", "li"),
        Pair("Malaysia", "my"),
        Pair("Mexico", "mx"),
        Pair("Morocco", "mo"),
        Pair("Netherlands", "nl"),
        Pair("New Zealand", "nz"),
        Pair("Nigeria", "ni"),
        Pair("Norway", "no"),
        Pair("Philippines", "ph"),
        Pair("Poland", "pl"),
        Pair("Portugal", "pt"),
        Pair("Romania", "ro"),
        Pair("Saudi Arabia", "sa"),
        Pair("Serbia", "rs"),
        Pair("Singapore", "sg"),
        Pair("Slovakia", "sk"),
        Pair("Slovenia", "sl"),
        Pair("South Africa", "za"),
        Pair("South Korea", "kr"),
        Pair("Sweden", "se"),
        Pair("Switzerland", "ch"),
        Pair("Taiwan", "tw"),
        Pair("Thailand", "th"),
        Pair("Turkey", "tr"),
        Pair("United Arab Emirates", "ae"),
        Pair("Ukraine", "ua"),
        Pair("United Kingdom", "gb"),
        Pair("United States", "us"),
        Pair("Venuzuela", "ue"),
    )
}